<?php $values = flash('old') ?: []; $value = static fn(string $key, mixed $default=''): mixed => $values[$key] ?? $default; ?>
<div class="admin-page-heading"><div><span class="admin-eyebrow">Envío programado</span><h1>Nueva campaña</h1><p>Cada destinatario recibirá un correo individual; nunca se expondrán direcciones entre sí.</p></div><a class="btn admin-secondary-btn" href="<?= url('/admin/email-marketing') ?>">Volver</a></div>
<?php if (!$deliverabilityReady): ?><div class="alert admin-alert admin-alert--error">La programación está bloqueada hasta configurar SMTP autenticado y validar SPF, DKIM y DMARC en el dominio remitente.</div><?php endif; ?>
<form class="admin-panel admin-form-panel" method="post" action="<?= url('/admin/email-marketing/crear') ?>"><?= csrf_field() ?>
    <div class="admin-form-section"><div><span>01</span><h2>Campaña</h2><p>Identificación, asunto y hora del primer envío.</p></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Nombre interno</label><input class="form-control" name="name" maxlength="160" required value="<?= e($value('name')) ?>" placeholder="Ej. Información DS N°44 agosto"></div><div class="col-md-6"><label class="form-label">Asunto del correo</label><input class="form-control" name="subject" maxlength="180" required value="<?= e($value('subject')) ?>"></div><div class="col-md-6"><label class="form-label">Inicio programado</label><input class="form-control" type="datetime-local" name="scheduled_at" required value="<?= e($value('scheduled_at', date('Y-m-d\TH:i', strtotime('+10 minutes')))) ?>"></div><div class="col-md-6"><label class="form-label">Separación entre correos</label><input class="form-control" value="10 minutos (fijo)" disabled><div class="form-text">La cola global impide enviar el siguiente correo antes de cumplir este plazo.</div></div></div></div>
    <div class="admin-form-section"><div><span>02</span><h2>Contenido</h2><p>Se insertará dentro de la plantilla corporativa editable.</p></div><div class="row g-3"><div class="col-12"><label class="form-label">Contenido HTML</label><textarea class="form-control marketing-code" name="content_html" rows="10" required placeholder="<p>Contenido útil para sus clientes...</p>"><?= e($value('content_html')) ?></textarea></div><div class="col-12"><label class="form-label">Versión de texto</label><textarea class="form-control" name="content_text" rows="6" required><?= e($value('content_text')) ?></textarea></div></div></div>
    <div class="admin-form-section"><div><span>03</span><h2>Destinatarios</h2><p>Use fuentes existentes o ingrese una dirección por línea.</p></div><div><div class="row g-3"><div class="col-12"><label class="form-label">Lista manual</label><textarea class="form-control" name="recipients" rows="8" placeholder="correo@empresa.cl&#10;Nombre,correo@empresa.cl,Empresa"><?= e($value('recipients')) ?></textarea><div class="form-text">Formatos admitidos: <code>correo@empresa.cl</code> o <code>Nombre,correo@empresa.cl,Empresa</code>. Se eliminan duplicados.</div></div><div class="col-md-6"><div class="form-check form-switch admin-switch"><input class="form-check-input" type="checkbox" id="include-clients" name="include_clients" value="1" <?= checked(isset($values['include_clients'])) ?>><label class="form-check-label" for="include-clients">Incluir clientes activos</label></div></div><div class="col-md-6"><div class="form-check form-switch admin-switch"><input class="form-check-input" type="checkbox" id="include-inquiries" name="include_inquiries" value="1" <?= checked(isset($values['include_inquiries'])) ?>><label class="form-check-label" for="include-inquiries">Incluir solicitudes web</label></div></div></div></div></div>
    <div class="admin-form-section"><div><span>04</span><h2>Confirmaciones</h2><p>Protegen la reputación del dominio y respetan la decisión de cada destinatario.</p></div><div class="d-grid gap-3"><div class="form-check"><input class="form-check-input" type="checkbox" id="consent-confirmed" name="consent_confirmed" value="1" <?= checked(isset($values['consent_confirmed'])) ?> required><label class="form-check-label" for="consent-confirmed">Confirmo que estos destinatarios autorizaron comunicaciones o mantienen una relación comercial legítima con PrevCapital.</label></div><div class="form-check"><input class="form-check-input" type="checkbox" id="warnings-reviewed" name="warnings_reviewed" value="1" <?= checked(isset($values['warnings_reviewed'])) ?>><label class="form-check-label" for="warnings-reviewed">Revisé el asunto, la proporción de texto, los enlaces y posibles expresiones asociadas a spam.</label></div></div></div>
    <div class="admin-form-actions"><a class="btn admin-secondary-btn" href="<?= url('/admin/email-marketing') ?>">Cancelar</a><button class="btn admin-primary-btn" type="submit" <?= $deliverabilityReady ? '' : 'disabled' ?>>Programar campaña</button></div>
</form>
