<?php $statusLabels = ['scheduled'=>'Programada','sending'=>'En curso','paused'=>'Pausada','completed'=>'Completada']; ?>
<div class="admin-page-heading">
    <div><span class="admin-eyebrow">Comunicación responsable</span><h1>Email Marketing</h1><p>Campañas individuales, trazables y separadas por un mínimo de 10 minutos.</p></div>
    <div class="admin-heading-actions"><?php if (\App\Core\Auth::can('marketing.manage')): ?><a class="btn admin-secondary-btn" href="<?= url('/admin/email-marketing/plantilla') ?>">Editar plantilla</a><a class="btn admin-primary-btn" href="<?= url('/admin/email-marketing/crear') ?>">Nueva campaña</a><?php endif; ?></div>
</div>
<div class="row g-4 admin-metrics">
    <div class="col-md-4"><article><div class="metric-icon metric-icon--teal"><svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM4 7l8 6 8-6"></path></svg></div><div><span>Suscritos</span><strong><?= (int) $counts['subscribed'] ?></strong><small>Disponibles para campañas</small></div></article></div>
    <div class="col-md-4"><article><div class="metric-icon"><svg viewBox="0 0 24 24"><path d="M5 12h14M12 5l7 7-7 7"></path></svg></div><div><span>Campañas</span><strong><?= count($campaigns) ?></strong><small>Historial de envíos</small></div></article></div>
    <div class="col-md-4"><article><div class="metric-icon"><svg viewBox="0 0 24 24"><path d="M5 5l14 14M19 5 5 19"></path></svg></div><div><span>Desuscritos</span><strong><?= (int) $counts['unsubscribed'] ?></strong><small>No volverán a recibir correos</small></div></article></div>
</div>
<div class="row g-4 mt-1">
    <div class="col-xl-8"><section class="admin-panel"><div class="admin-panel__header"><div><span class="admin-eyebrow">Programación</span><h2>Campañas</h2></div><?php if (\App\Core\Auth::can('marketing.send')): ?><form method="post" action="<?= url('/admin/email-marketing/procesar') ?>"><?= csrf_field() ?><button class="btn admin-secondary-btn" type="submit">Procesar siguiente envío</button></form><?php endif; ?></div><div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th>Campaña</th><th>Progreso</th><th>Inicio</th><th>Estado</th><th class="text-end">Acción</th></tr></thead><tbody><?php foreach ($campaigns as $campaign): ?><tr><td><strong><?= e($campaign['name']) ?></strong><small class="d-block"><?= e($campaign['subject']) ?></small></td><td><?= (int) $campaign['sent_count'] ?> / <?= (int) $campaign['total_recipients'] ?><?php if ((int) $campaign['failed_count']): ?><small class="d-block text-danger"><?= (int) $campaign['failed_count'] ?> fallidos</small><?php endif; ?></td><td><?= e(date('d/m/Y H:i', strtotime($campaign['scheduled_at']))) ?></td><td><span class="status-badge status-<?= e($campaign['status']) ?>"><?= e($statusLabels[$campaign['status']] ?? $campaign['status']) ?></span></td><td class="text-end"><a class="btn admin-icon-btn ms-auto" href="<?= url('/admin/email-marketing/ver?id=' . (int) $campaign['id']) ?>" aria-label="Ver campaña"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"></path><circle cx="12" cy="12" r="2.5"></circle></svg></a></td></tr><?php endforeach; ?><?php if (!$campaigns): ?><tr><td colspan="5" class="empty-cell">Aún no existen campañas.</td></tr><?php endif; ?></tbody></table></div></section></div>
    <div class="col-xl-4"><section class="admin-panel deliverability-panel"><div class="admin-panel__header"><div><span class="admin-eyebrow">Entregabilidad</span><h2>Control anti-spam</h2></div></div><div class="deliverability-list"><?php foreach ($deliverability as $check): ?><article class="<?= $check['ok'] ? 'is-ok' : 'is-warning' ?>"><span><?= $check['ok'] ? '✓' : '!' ?></span><div><strong><?= e($check['label']) ?></strong><p><?= e($check['detail']) ?></p></div></article><?php endforeach; ?></div><p class="admin-meta p-4 pt-0 mb-0">La bandeja de entrada nunca puede garantizarse al 100 %. SMTP, SPF, DKIM, DMARC, consentimiento, baja automática y ritmo controlado reducen sustancialmente el riesgo.</p></section></div>
</div>
