<?php
$isEdit = $client !== null;
$values = flash('old') ?: [];
$value = static fn (string $key, mixed $default = ''): mixed => $values[$key] ?? ($client[$key] ?? $default);
$statusChecked = $values ? isset($values['status']) : (!$isEdit || (int) ($client['status'] ?? 1) === 1);
?>
<div class="admin-page-heading"><div><span class="admin-eyebrow">Gestión comercial</span><h1><?= $isEdit ? 'Editar cliente' : 'Nuevo cliente' ?></h1><p>Registre una vez los datos y reutilícelos en futuras cotizaciones.</p></div><a class="btn admin-secondary-btn" href="<?= url('/admin/clientes') ?>">Volver</a></div>
<form class="admin-panel admin-form-panel" method="post" action="<?= $isEdit ? url('/admin/clientes/editar?id=' . (int) $client['id']) : url('/admin/clientes/crear') ?>">
    <?= csrf_field() ?>
    <div class="admin-form-section"><div><span>01</span><h2>Identificación</h2><p>Datos principales de la organización y su contacto.</p></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="company">Empresa</label><input class="form-control" id="company" name="company" maxlength="160" required value="<?= e($value('company')) ?>"></div><div class="col-md-6"><label class="form-label" for="name">Nombre de contacto</label><input class="form-control" id="name" name="name" maxlength="140" required value="<?= e($value('name')) ?>"></div><div class="col-md-6"><label class="form-label" for="email">Correo</label><input class="form-control" id="email" type="email" name="email" maxlength="180" required value="<?= e($value('email')) ?>"></div><div class="col-md-3"><label class="form-label" for="phone">Teléfono</label><input class="form-control" id="phone" name="phone" maxlength="60" value="<?= e($value('phone')) ?>"></div><div class="col-md-3"><label class="form-label" for="tax_id">RUT</label><input class="form-control" id="tax_id" name="tax_id" maxlength="30" value="<?= e($value('tax_id')) ?>"></div></div></div>
    <div class="admin-form-section"><div><span>02</span><h2>Información comercial</h2><p>Dirección, notas internas y disponibilidad del cliente.</p></div><div class="row g-3"><div class="col-12"><label class="form-label" for="address">Dirección</label><input class="form-control" id="address" name="address" maxlength="255" value="<?= e($value('address')) ?>"></div><div class="col-12"><label class="form-label" for="notes">Notas internas</label><textarea class="form-control" id="notes" name="notes" maxlength="3000" rows="3"><?= e($value('notes')) ?></textarea></div><div class="col-12"><div class="form-check form-switch admin-switch"><input class="form-check-input" id="status" type="checkbox" name="status" value="1" <?= checked($statusChecked) ?>><label class="form-check-label" for="status">Cliente activo y disponible al crear cotizaciones</label></div></div></div></div>
    <div class="admin-form-actions"><a class="btn admin-secondary-btn" href="<?= url('/admin/clientes') ?>">Cancelar</a><button class="btn admin-primary-btn" type="submit"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"></path></svg><?= $isEdit ? 'Guardar cambios' : 'Crear cliente' ?></button></div>
</form>
