<?php $statusLabels = ['draft' => 'En preparación', 'sent' => 'Pendiente de respuesta', 'accepted' => 'Aceptada', 'rejected' => 'Rechazada']; ?>
<section class="web-quote-hero"><div class="container"><p>Cotización digital · <?= e($quote['quote_number']) ?></p><h1><?= e($quote['subject']) ?></h1><span>Preparada para <?= e($quote['company']) ?></span></div></section>
<section class="web-quote section"><div class="container web-quote__layout"><div>
    <?php if ($message = flash('success')): ?><div class="web-quote-notice web-quote-notice--success" role="status"><?= e($message) ?></div><?php endif; ?>
    <?php if ($message = flash('error')): ?><div class="web-quote-notice web-quote-notice--error" role="alert"><?= e($message) ?></div><?php endif; ?>
    <section class="web-quote-card"><div class="web-quote-card__top"><div><span>Propuesta PrevCapital</span><strong><?= e($quote['quote_number']) ?></strong></div><span class="web-status web-status--<?= e($quote['status']) ?>"><?= e($statusLabels[$quote['status']] ?? '') ?></span></div>
        <div class="web-quote-client"><div><span>Cliente</span><strong><?= e($quote['company']) ?></strong><p><?= e($quote['client_name']) ?></p></div><div><span>Emisión</span><strong><?= e(date('d/m/Y', strtotime($quote['issue_date']))) ?></strong></div><div><span>Válida hasta</span><strong><?= e(date('d/m/Y', strtotime($quote['valid_until']))) ?></strong></div></div>
        <div class="web-quote-table-wrap"><table class="web-quote-table"><thead><tr><th>Servicio</th><th>Cantidad</th><th>Valor</th><th>Total</th></tr></thead><tbody><?php foreach ($quote['items'] as $item): ?><tr><td><strong><?= e($item['description']) ?></strong><?php if ($item['detail']): ?><small><?= e($item['detail']) ?></small><?php endif; ?></td><td><?= e(rtrim(rtrim(number_format((float) $item['quantity'], 2, ',', '.'), '0'), ',')) ?></td><td><?= money_clp($item['unit_price']) ?></td><td><strong><?= money_clp($item['total']) ?></strong></td></tr><?php endforeach; ?></tbody></table></div>
        <div class="web-quote-totals"><div><span>Subtotal</span><strong><?= money_clp($quote['subtotal']) ?></strong></div><?php if ((float) ($quote['discount_amount'] ?? 0) > 0): ?><div><span>Descuento<?= ($quote['discount_type'] ?? '') === 'percentage' ? ' ' . e(rtrim(rtrim(number_format((float) $quote['discount_value'], 2, ',', '.'), '0'), ',')) . '%' : '' ?></span><strong>-<?= money_clp($quote['discount_amount']) ?></strong></div><?php endif; ?><div><span>IVA <?= e(rtrim(rtrim(number_format((float) $quote['tax_rate'], 2, ',', '.'), '0'), ',')) ?>%</span><strong><?= money_clp($quote['tax_amount']) ?></strong></div><div><span>Total</span><strong><?= money_clp($quote['total']) ?></strong></div></div>
        <?php if ($quote['notes'] || $quote['terms']): ?><div class="web-quote-conditions"><?php if ($quote['notes']): ?><div><span>Observaciones</span><p><?= nl2br(e($quote['notes'])) ?></p></div><?php endif; ?><?php if ($quote['terms']): ?><div><span>Condiciones</span><p><?= nl2br(e($quote['terms'])) ?></p></div><?php endif; ?></div><?php endif; ?>
    </section>
</div><aside class="web-quote-actions">
    <div><span class="section-kicker">Respuesta digital</span>
    <?php if ($quote['status'] === 'sent'): ?><h2>Revise y responda la propuesta.</h2><p>Su elección quedará registrada y será informada automáticamente a PrevCapital.</p><form method="post" action="<?= url('/cotizacion/responder') ?>" onsubmit="return confirm('¿Confirma que desea aceptar esta cotización?')"><?= csrf_field() ?><input type="hidden" name="token" value="<?= e($quote['public_token']) ?>"><input type="hidden" name="decision" value="accepted"><button class="button button--primary button--full" type="submit">Aceptar cotización</button></form><form class="web-quote-reject" method="post" action="<?= url('/cotizacion/responder') ?>" onsubmit="return confirm('¿Confirma que desea rechazar esta cotización?')"><?= csrf_field() ?><input type="hidden" name="token" value="<?= e($quote['public_token']) ?>"><input type="hidden" name="decision" value="rejected"><label>Motivo u observación<textarea name="reason" maxlength="1000" rows="3" placeholder="Opcional"></textarea></label><button class="button button--outline button--full" type="submit">Rechazar cotización</button></form>
    <?php elseif ($quote['status'] === 'accepted'): ?><div class="web-final-state web-final-state--accepted"><span>✓</span><h2>Cotización aceptada</h2><p>Registrada el <?= e(date('d/m/Y \a \l\a\s H:i', strtotime($quote['accepted_at']))) ?>. Nuestro equipo coordinará los próximos pasos.</p></div>
    <?php elseif ($quote['status'] === 'rejected'): ?><div class="web-final-state web-final-state--rejected"><span>×</span><h2>Respuesta registrada</h2><p>La cotización fue rechazada el <?= e(date('d/m/Y \a \l\a\s H:i', strtotime($quote['rejected_at']))) ?>. Podemos revisar el alcance con usted.</p></div>
    <?php else: ?><div class="web-final-state"><h2>Propuesta en preparación</h2><p>La respuesta quedará habilitada cuando PrevCapital envíe formalmente la cotización.</p></div><?php endif; ?>
    <a class="web-pdf-link" target="_blank" href="<?= url('/cotizacion/pdf?token=' . e($quote['public_token'])) ?>">Descargar cotización en PDF</a></div>
</aside></div></section>
