<?php $statusLabels = ['draft' => 'Borrador', 'sent' => 'Enviada', 'accepted' => 'Aceptada', 'rejected' => 'Rechazada']; ?>
<div class="admin-page-heading"><div><span class="admin-eyebrow">Gestión comercial</span><h1>Cotizaciones</h1><p>Cree propuestas, envíelas y supervise la respuesta del cliente.</p></div><?php if (\App\Core\Auth::can('quotes.create')): ?><a class="btn admin-primary-btn" href="<?= url('/admin/cotizaciones/crear') ?>">Nueva cotización</a><?php endif; ?></div>
<section class="admin-panel">
    <form class="admin-filters" method="get" action="<?= url('/admin/cotizaciones') ?>"><input class="form-control" name="search" value="<?= e($search) ?>" placeholder="Buscar número, empresa, contacto o asunto"><select class="form-select" name="status"><option value="">Todos los estados</option><?php foreach ($statusLabels as $value => $label): ?><option value="<?= e($value) ?>" <?= selected($status, $value) ?>><?= e($label) ?></option><?php endforeach; ?></select><button class="btn admin-secondary-btn" type="submit">Filtrar</button></form>
    <div class="table-responsive"><table class="table admin-table align-middle mb-0"><thead><tr><th>Número</th><th>Cliente</th><th>Asunto</th><th>Total</th><th>Vigencia</th><th>Estado</th><th class="text-end">Acción</th></tr></thead><tbody>
    <?php foreach ($quotes as $quote): ?><tr><td><strong><?= e($quote['quote_number']) ?></strong><small class="d-block text-muted"><?= e(date('d/m/Y', strtotime($quote['issue_date']))) ?></small></td><td><strong><?= e($quote['company']) ?></strong><small class="d-block text-muted"><?= e($quote['client_name']) ?></small></td><td><?= e($quote['subject']) ?></td><td><strong><?= money_clp($quote['total']) ?></strong></td><td><?= e(date('d/m/Y', strtotime($quote['valid_until']))) ?></td><td><span class="status-badge status-<?= e($quote['status']) ?>"><?= e($statusLabels[$quote['status']] ?? '') ?></span></td><td class="text-end"><a class="btn admin-icon-btn ms-auto" href="<?= url('/admin/cotizaciones/ver?id=' . (int) $quote['id']) ?>" title="Ver cotización" aria-label="Ver cotización"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"></path><circle cx="12" cy="12" r="2.5"></circle></svg></a></td></tr><?php endforeach; ?>
    <?php if (!$quotes): ?><tr><td class="empty-cell" colspan="7">No hay cotizaciones que coincidan con los filtros.</td></tr><?php endif; ?>
    </tbody></table></div>
</section>
